### ISSUE TITLE
INFOGRAFIA - GESTION DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-CxrlosMX#2]
![Infografia - Luis Carlos Rendon](https://user-images.githubusercontent.com/77459857/186517595-bf8605af-0db4-4870-a350-48e9d73f8cd7.jpg)

**Comment by Brisa-4** [comment]
Calificación 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
